// models/MealPlan.js
const mongoose = require("mongoose");

const MealEntry = new mongoose.Schema({
  date: { type: Date, required: true }, // specific day
  mealSlot: { type: String, enum: ["breakfast", "lunch", "dinner", "snack"] },
  recipe: { type: mongoose.Schema.Types.ObjectId, ref: "Recipe" },
  notes: String,
});

const MealPlanSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    title: String, // "Week of 2025-05-04"
    startDate: Date,
    endDate: Date,
    entries: [MealEntry],
    isAutoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

module.exports = mongoose.model("MealPlan", MealPlanSchema);
